version: "3.5"

services:
  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mk_sql_test

  php:
    build: .
    volumes:
      - ./:/var/www/html

