<?php declare(strict_types=1);

namespace Mock;

class PDO extends \PDO
{

    public function __construct()
    {
        parent::__construct("sqlite::memory:",null,null,null);
    }

    public function getAttribute($attribute)
    {
        if($attribute === PDO::ATTR_DRIVER_NAME)
        {
            return "mysql";
        }
        return parent::getAttribute($attribute); // TODO: Change the autogenerated stub
    }

    public function __call($name_of_function, $arguments)
    {
        echo "MockCalled: ".$name_of_function.var_export($arguments).PHP_EOL;
    }
}